<?xml version="1.0" encoding="utf-8" ?>
<Project>
	<PropertyGroup>
		<GamePath>D:\Steam\steamapps\common\Gorilla Tag</GamePath>
		<GameAssemblyPath>D:\Steam\steamapps\common\Gorilla Tag\Gorilla Tag_Data\Managed</GameAssemblyPath>
		<BepInExAssemblyPath>D:\Steam\steamapps\common\Gorilla Tag\BepInEx\core</BepInExAssemblyPath>
		<PluginsPath>D:\Steam\steamapps\common\Gorilla Tag\BepInEx\plugins</PluginsPath>
	</PropertyGroup>
	<PropertyGroup Condition="'$(CI)'=='TRUE'">
		<GameAssemblyPath>.\Libs</GameAssemblyPath>
		<BepInExAssemblyPath>.\Libs</BepInExAssemblyPath>
		<PluginsPath>.\Libs</PluginsPath>
		<WarningLevel>0</WarningLevel>
	</PropertyGroup>
</Project>
